---
## Installation options
app_root_path: /app

redis_version: 3.2.1
redis_source_dir: "/usr/local/src"
redis_source_tar_gz_file_name: "redis-{{redis_version}}.tar.gz"
redis_source_tar_gz_file_path: "{{redis_source_dir}}/{{redis_source_tar_gz_file_name}}"
redis_source_path: "{{redis_source_dir}}/redis-{{redis_version}}"
redis_log_dir: "{{redis_home}}/log"
redis_user: "{{username}}"
redis_group: "{{usergroup}}"

redis_verify_checksum: false
redis_download_url: "http://download.redis.io/releases/redis-{{redis_version}}.tar.gz"
redis_tar_file: "redis-{{redis_version}}.tar.gz"
# The open file limit for Redis/Sentinel
redis_nofile_limit: 16384

## Role options
# Configure Redis as a service
# This creates the init scripts for Redis and ensures the process is running
# Also applies for Redis Sentinel
redis_as_service: true
# Add local facts to /etc/ansible/facts.d for Redis
redis_local_facts: true
# Service name
redis_service_name: "redis_{{ redis_port }}.service"

## Networking/connection options
redis_bind: "{{innerip | default('127.0.0.1')}}"
redis_port: 6389
redis_home: "/app/redis{{redis_port}}-bin"
redis_conf_path: "{{redis_home}}/redis_{{redis_port}}.conf"
redis_pidfile: "{{redis_home}}/{{ redis_port }}.pid"
redis_dir: "{{redis_home}}"
# redis_password: xxxxx
# Slave replication options
redis_min_slaves_to_write: 0
redis_min_slaves_max_lag: 10
redis_tcp_backlog: 511
redis_tcp_keepalive: 0
# Max connected clients at a time
redis_maxclients: 10000
redis_timeout: 0
# Socket options
# Set socket_path to the desired path to the socket. E.g. /var/run/redis/{{ redis_port }}.sock
redis_socket_path: false
redis_socket_perm: 755

## Replication options
# Set slaveof just as you would in redis.conf. (e.g. "redis01 6379")
redis_slaveof: false
# Make slaves read-only. "yes" or "no"
redis_slave_read_only: "yes"
redis_slave_priority: 100
redis_repl_backlog_size: false

## Logging
redis_logfile: '{{redis_log_dir}}/redis.log'
# Enable syslog. "yes" or "no"
redis_syslog_enabled: "no"
redis_syslog_ident: "{{ redis_service_name }}"
# Syslog facility. Must be USER or LOCAL0-LOCAL7
redis_syslog_facility: USER

## General configuration
redis_daemonize: "yes"

# Number of databases to allow
redis_databases: 16
redis_loglevel: debug
# Log queries slower than this many milliseconds. -1 to disable
redis_slowlog_log_slower_than: 10000
# Maximum number of slow queries to save
redis_slowlog_max_len: 128
# Redis memory limit (e.g. 4294967296, 4096mb, 4gb)
redis_maxmemory: false
redis_maxmemory_policy: noeviction
redis_rename_commands: []
# How frequently to snapshot the database to disk
# e.g. "900 1" => 900 seconds if at least 1 key changed
redis_save: ""
# redis_save:
#   - 900 1
#   - 300 10
#   - 60 10000
redis_appendonly: "no"
redis_appendfilename: "appendonly.aof"
redis_appendfsync: "everysec"
redis_no_appendfsync_on_rewrite: "no"
redis_auto_aof_rewrite_percentage: "100"
redis_auto_aof_rewrite_min_size: "64mb"
